{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "state": "PUBLISHED",
        "cveId": "CVE-2022-1632",
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "dateUpdated": "2024-07-04T01:23:20.555Z",
        "dateReserved": "2022-05-09T00:00:00",
        "datePublished": "2022-09-01T00:00:00"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat",
                "dateUpdated": "2022-12-08T00:00:00"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "An Improper Certificate Validation attack was found in Openshift. A re-encrypt Route with destinationCACertificate explicitly set to the default serviceCA skips internal Service TLS certificate validation. This flaw allows an attacker to exploit an invalid certificate, resulting in a loss of confidentiality."
                }
            ],
            "affected": [
                {
                    "vendor": "n/a",
                    "product": "Openshift",
                    "versions": [
                        {
                            "version": "4.8.17",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "references": [
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2081181"
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "CWE",
                            "lang": "en",
                            "description": "CWE-295",
                            "cweId": "CWE-295"
                        }
                    ]
                }
            ]
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "96f1cf3c-f80a-4e0f-a063-99a91e3f1325",
                    "shortName": "secretariat-reference",
                    "dateUpdated": "2024-07-04T01:23:20.555Z"
                },
                "references": [
                    {
                        "name": "Test (1519/24750) [1519/3750] <1/4>",
                        "tags": [
                            "x_test_run_data",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://example.org/CVE-2022-1632"
                    },
                    {
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2081181/DEMO_2024_06_19",
                        "tags": [
                            "x_cve_prog_secretariat_snapshot"
                        ]
                    },
                    {
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2081181/adp-test-6-28",
                        "tags": [
                            "x_snapshot"
                        ]
                    }
                ]
            }
        ]
    }
}