{
    "dataType": "CVE_RECORD",
    "cveMetadata": {
        "cveId": "CVE-2024-4032",
        "assignerOrgId": "28c92f92-d60d-412d-b760-e73465c3df22",
        "state": "PUBLISHED",
        "assignerShortName": "PSF",
        "dateReserved": "2024-04-22T17:15:47.895Z",
        "datePublished": "2024-06-17T15:05:58.827Z",
        "dateUpdated": "2024-09-17T15:55:55.506Z"
    },
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unaffected",
                    "product": "CPython",
                    "repo": "https://github.com/python/cpython",
                    "vendor": "Python Software Foundation",
                    "versions": [
                        {
                            "version": "0",
                            "lessThan": "3.8.20",
                            "status": "affected",
                            "versionType": "python"
                        },
                        {
                            "version": "3.9.0",
                            "lessThan": "3.9.20",
                            "status": "affected",
                            "versionType": "python"
                        },
                        {
                            "version": "3.10.0",
                            "lessThan": "3.10.15",
                            "status": "affected",
                            "versionType": "python"
                        },
                        {
                            "version": "3.11.0",
                            "lessThan": "3.11.10",
                            "status": "affected",
                            "versionType": "python"
                        },
                        {
                            "version": "3.12.0",
                            "lessThan": "3.12.4",
                            "status": "affected",
                            "versionType": "python"
                        },
                        {
                            "version": "3.13.0a1",
                            "lessThan": "3.13.0a6",
                            "status": "affected",
                            "versionType": "python"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "supportingMedia": [
                        {
                            "base64": false,
                            "type": "text/html",
                            "value": "<p><span style=\"background-color: transparent;\">The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.</span></p><p><span style=\"background-color: transparent;\">CPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.</span></p>"
                        }
                    ],
                    "value": "The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\n\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior."
                }
            ],
            "providerMetadata": {
                "orgId": "28c92f92-d60d-412d-b760-e73465c3df22",
                "shortName": "PSF",
                "dateUpdated": "2024-09-07T02:44:42.321Z"
            },
            "references": [
                {
                    "tags": [
                        "issue-tracking"
                    ],
                    "url": "https://github.com/python/cpython/issues/113171"
                },
                {
                    "tags": [
                        "patch"
                    ],
                    "url": "https://github.com/python/cpython/pull/113179"
                },
                {
                    "url": "https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml"
                },
                {
                    "url": "https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml"
                },
                {
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/"
                },
                {
                    "tags": [
                        "patch"
                    ],
                    "url": "https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8"
                },
                {
                    "tags": [
                        "patch"
                    ],
                    "url": "https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f"
                },
                {
                    "tags": [
                        "patch"
                    ],
                    "url": "https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3"
                },
                {
                    "tags": [
                        "patch"
                    ],
                    "url": "https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb"
                },
                {
                    "tags": [
                        "patch"
                    ],
                    "url": "https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906"
                },
                {
                    "tags": [
                        "patch"
                    ],
                    "url": "https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2024/06/17/3"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20240726-0004/"
                }
            ],
            "source": {
                "discovery": "UNKNOWN"
            },
            "title": "Incorrect IPv4 and IPv6 private ranges",
            "x_generator": {
                "engine": "Vulnogram 0.2.0"
            }
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "af854a3a-2127-422b-91ae-364da2661108",
                    "shortName": "CVE",
                    "dateUpdated": "2024-08-01T20:26:57.360Z"
                },
                "title": "CVE Program Container",
                "references": [
                    {
                        "tags": [
                            "issue-tracking",
                            "x_transferred"
                        ],
                        "url": "https://github.com/python/cpython/issues/113171"
                    },
                    {
                        "tags": [
                            "patch",
                            "x_transferred"
                        ],
                        "url": "https://github.com/python/cpython/pull/113179"
                    },
                    {
                        "url": "https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml",
                        "tags": [
                            "x_transferred"
                        ]
                    },
                    {
                        "url": "https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml",
                        "tags": [
                            "x_transferred"
                        ]
                    },
                    {
                        "tags": [
                            "vendor-advisory",
                            "x_transferred"
                        ],
                        "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/"
                    },
                    {
                        "tags": [
                            "patch",
                            "x_transferred"
                        ],
                        "url": "https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8"
                    },
                    {
                        "tags": [
                            "patch",
                            "x_transferred"
                        ],
                        "url": "https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f"
                    },
                    {
                        "tags": [
                            "patch",
                            "x_transferred"
                        ],
                        "url": "https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3"
                    },
                    {
                        "tags": [
                            "patch",
                            "x_transferred"
                        ],
                        "url": "https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb"
                    },
                    {
                        "tags": [
                            "patch",
                            "x_transferred"
                        ],
                        "url": "https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906"
                    },
                    {
                        "tags": [
                            "patch",
                            "x_transferred"
                        ],
                        "url": "https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3"
                    },
                    {
                        "url": "http://www.openwall.com/lists/oss-security/2024/06/17/3",
                        "tags": [
                            "x_transferred"
                        ]
                    },
                    {
                        "url": "https://security.netapp.com/advisory/ntap-20240726-0004/",
                        "tags": [
                            "x_transferred"
                        ]
                    }
                ]
            },
            {
                "problemTypes": [
                    {
                        "descriptions": [
                            {
                                "type": "CWE",
                                "cweId": "CWE-697",
                                "lang": "en",
                                "description": "CWE-697 Incorrect Comparison"
                            }
                        ]
                    }
                ],
                "affected": [
                    {
                        "vendor": "python",
                        "product": "cpython",
                        "cpes": [
                            "cpe:2.3:a:python:cpython:*:*:*:*:*:*:*:*"
                        ],
                        "defaultStatus": "unknown",
                        "versions": [
                            {
                                "version": "0",
                                "status": "affected",
                                "lessThan": "3.12.4",
                                "versionType": "custom"
                            },
                            {
                                "version": "3.13.0a1",
                                "status": "affected",
                                "lessThan": "3.13.0a6",
                                "versionType": "custom"
                            }
                        ]
                    }
                ],
                "metrics": [
                    {
                        "cvssV3_1": {
                            "scope": "UNCHANGED",
                            "version": "3.1",
                            "baseScore": 7.5,
                            "attackVector": "NETWORK",
                            "baseSeverity": "HIGH",
                            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                            "integrityImpact": "NONE",
                            "userInteraction": "NONE",
                            "attackComplexity": "LOW",
                            "availabilityImpact": "NONE",
                            "privilegesRequired": "NONE",
                            "confidentialityImpact": "HIGH"
                        }
                    },
                    {
                        "other": {
                            "type": "ssvc",
                            "content": {
                                "timestamp": "2024-08-08T18:21:11.207929Z",
                                "id": "CVE-2024-4032",
                                "options": [
                                    {
                                        "Exploitation": "none"
                                    },
                                    {
                                        "Automatable": "yes"
                                    },
                                    {
                                        "Technical Impact": "partial"
                                    }
                                ],
                                "role": "CISA Coordinator",
                                "version": "2.0.3"
                            }
                        }
                    }
                ],
                "title": "CISA ADP Vulnrichment",
                "providerMetadata": {
                    "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
                    "shortName": "CISA-ADP",
                    "dateUpdated": "2024-09-17T15:55:55.506Z"
                }
            }
        ]
    },
    "dataVersion": "5.1"
}