{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-07-20T10:06:23",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://blog.jetbrains.com"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://blog.jetbrains.com/blog/2021/05/07/jetbrains-security-bulletin-q1-2021/"
                },
                {
                    "name": "GLSA-202107-45",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_GENTOO"
                    ],
                    "url": "https://security.gentoo.org/glsa/202107-45"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2021-30005",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://blog.jetbrains.com",
                            "refsource": "MISC",
                            "url": "https://blog.jetbrains.com"
                        },
                        {
                            "name": "https://blog.jetbrains.com/blog/2021/05/07/jetbrains-security-bulletin-q1-2021/",
                            "refsource": "MISC",
                            "url": "https://blog.jetbrains.com/blog/2021/05/07/jetbrains-security-bulletin-q1-2021/"
                        },
                        {
                            "name": "GLSA-202107-45",
                            "refsource": "GENTOO",
                            "url": "https://security.gentoo.org/glsa/202107-45"
                        }
                    ]
                }
            }
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "96f1cf3c-f80a-4e0f-a063-99a91e3f1325",
                    "shortName": "secretariat-reference",
                    "dateUpdated": "2024-07-03T16:41:40.067Z"
                },
                "references": [
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://blog.jetbrains.com/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://blog.jetbrains.com/blog/2021/05/07/jetbrains-security-bulletin-q1-2021//DEMO_2024_06_19"
                    },
                    {
                        "name": "GLSA-202107-45",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_GENTOO",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://security.gentoo.org/glsa/202107-45/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_snapshot"
                        ],
                        "url": "https://blog.jetbrains.com/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_snapshot"
                        ],
                        "url": "https://blog.jetbrains.com/blog/2021/05/07/jetbrains-security-bulletin-q1-2021//adp-test-6-28"
                    },
                    {
                        "name": "GLSA-202107-45",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_GENTOO",
                            "x_snapshot"
                        ],
                        "url": "https://security.gentoo.org/glsa/202107-45/adp-test-6-28"
                    }
                ]
            }
        ]
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2021-30005",
        "datePublished": "2021-05-11T11:42:55",
        "dateReserved": "2021-04-02T00:00:00",
        "dateUpdated": "2024-07-03T16:41:40.067Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1"
}