{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2012-04-19T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Python 2.7 before 3.4 only uses the last eight bits of the prefix to randomize hash values, which causes it to compute hash values without restricting the ability to trigger hash collisions predictably and makes it easier for context-dependent attackers to cause a denial of service (CPU consumption) via crafted input to an application that maintains a hash table.  NOTE: this vulnerability exists because of an incomplete fix for CVE-2012-1150."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2016-11-25T19:57:01",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "64194",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_BID"
                    ],
                    "url": "http://www.securityfocus.com/bid/64194"
                },
                {
                    "name": "[oss-security] 20131209 Re: CPython hash secret can be recoved remotely",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2013/12/09/13"
                },
                {
                    "name": "[oss-security] 20131209 CPython hash secret can be recoved remotely",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2013/12/09/3"
                },
                {
                    "name": "APPLE-SA-2015-08-13-2",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_APPLE"
                    ],
                    "url": "http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "http://bugs.python.org/issue14621"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://support.apple.com/kb/HT205031"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2013-7040",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "Python 2.7 before 3.4 only uses the last eight bits of the prefix to randomize hash values, which causes it to compute hash values without restricting the ability to trigger hash collisions predictably and makes it easier for context-dependent attackers to cause a denial of service (CPU consumption) via crafted input to an application that maintains a hash table.  NOTE: this vulnerability exists because of an incomplete fix for CVE-2012-1150."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "64194",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/64194"
                        },
                        {
                            "name": "[oss-security] 20131209 Re: CPython hash secret can be recoved remotely",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2013/12/09/13"
                        },
                        {
                            "name": "[oss-security] 20131209 CPython hash secret can be recoved remotely",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2013/12/09/3"
                        },
                        {
                            "name": "APPLE-SA-2015-08-13-2",
                            "refsource": "APPLE",
                            "url": "http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html"
                        },
                        {
                            "name": "http://bugs.python.org/issue14621",
                            "refsource": "CONFIRM",
                            "url": "http://bugs.python.org/issue14621"
                        },
                        {
                            "name": "https://support.apple.com/kb/HT205031",
                            "refsource": "CONFIRM",
                            "url": "https://support.apple.com/kb/HT205031"
                        }
                    ]
                }
            }
        },
        "adp": [
            {
                "references": [
                    {
                        "url": "http://www.securityfocus.com/bid/64194"
                    },
                    {
                        "name": "64194",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_BID",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.securityfocus.com/bid/64194/DEMO_2024_06_19"
                    },
                    {
                        "name": "[oss-security] 20131209 Re: CPython hash secret can be recoved remotely",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2013/12/09/13/DEMO_2024_06_19"
                    },
                    {
                        "name": "[oss-security] 20131209 CPython hash secret can be recoved remotely",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2013/12/09/3/DEMO_2024_06_19"
                    },
                    {
                        "name": "APPLE-SA-2015-08-13-2",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_APPLE",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://bugs.python.org/issue14621/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://support.apple.com/kb/HT205031/DEMO_2024_06_19"
                    },
                    {
                        "name": "64194",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_BID",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.securityfocus.com/bid/64194/adp-test-6-28"
                    },
                    {
                        "name": "[oss-security] 20131209 Re: CPython hash secret can be recoved remotely",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2013/12/09/13/adp-test-6-28"
                    },
                    {
                        "name": "[oss-security] 20131209 CPython hash secret can be recoved remotely",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.openwall.com/lists/oss-security/2013/12/09/3/adp-test-6-28"
                    },
                    {
                        "name": "APPLE-SA-2015-08-13-2",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_APPLE",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://bugs.python.org/issue14621/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://support.apple.com/kb/HT205031/adp-test-6-28"
                    }
                ],
                "providerMetadata": {
                    "orgId": "96f1cf3c-f80a-4e0f-a063-99a91e3f1325",
                    "shortName": "secretariat-reference",
                    "dateUpdated": "2024-06-30T05:42:14.778Z"
                }
            }
        ]
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2013-7040",
        "datePublished": "2014-05-19T14:00:00",
        "dateReserved": "2013-12-09T00:00:00",
        "dateUpdated": "2024-06-30T05:42:14.778Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1"
}